# Lab-3

## 1. Write a numpy program to get the numpy version and show numpy build configuration

In [1]:
import numpy
print("Version : ",numpy.__version__)
print("Build Configuration : ")
numpy.show_config()

Version :  1.21.5
Build Configuration : 
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/pawan/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/pawan/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/pawan/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/pawan/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/pawan/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/pawan/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/pawan/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/pawan/anaconda3\\Library\\include']
Supported S

## 2. Write a NumPy Program to test whether any of the elements of a given array is non zero

In [15]:
import numpy as np
arr=np.array([0,1,2,3,0,0,0,0,0,0])
print(arr)
print("The Non-zero elements are : ")
print(arr[numpy.nonzero(arr)])

[0 1 2 3 0 0 0 0 0 0]
The Non-zero elements are : 
[1 2 3]


## 3. Write a NumPy program to test element-wise for complex number, real number of a given array. Also test whether a given number is a scalar type or not 

In [22]:
import numpy as np
a = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])
print("Original array: ",a)
print("The complex numbers are : ",np.iscomplex(a))
print("The real numbers are : ",np.isreal(a))
print("Scalar numbers : ",np.isscalar(a))

Original array:  [1. +1.j 1. +0.j 4.5+0.j 3. +0.j 2. +0.j 0. +2.j]
The complex numbers are :  [ True False False False False  True]
The real numbers are :  [False  True  True  True  True False]
Scalar numbers :  False


## 4. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution

In [2]:
import numpy as np
arr=np.random.normal(0,1,15)
print(arr)

[-0.38449084 -0.05493805  1.47244126  0.34378406  0.53638604  0.40500352
 -0.93501922  0.67550448 -0.6881544  -0.13125439  0.86087192 -0.27446063
  0.47586038 -1.21570153 -0.05353601]


## 5. Write a NumPy program to create a 3*3 identity matrix, i.e. diagonal elements are 1 and the rest are 0

In [25]:
import numpy as np
arr=np.identity(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 6. Write a NumPy program to create 5*5 zero matrix with elements on the main diagonal 1,2,3,4,5

In [27]:
import numpy as np
arr=np.diag([1,2,3,4,5])
print(arr)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


## 7. Extract all numbers greater than and lesser than a specified number in a list

In [32]:
import numpy as np
arr=np.array([0,1,2,3,0,0,0,0,0,0])
print(arr)
n=2
print("Numbers greater than n ")
print(arr>n)
print("Numbers lesser than n ")
print(arr<n)


[0 1 2 3 0 0 0 0 0 0]
Numbers greater than n 
[False False False  True False False False False False False]
Numbers lesser than n 
[ True  True False False  True  True  True  True  True  True]


## 8. Create a 4*4 array, now create a new array from the said array swapping first and last, second and third columns

In [37]:
import numpy as np 
nums = np.arange(16, dtype='int').reshape(4, 4)
print("Original array:")
print(nums)
print("After Swapping :")
new_nums = nums[:, ::-1]
print(new_nums)

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
After Swapping :
[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]
